name: bootstrap_for_pub
description: Just Bootstrap's files, in a pub package.
authors:
- Bootstrap core team
version: 3.1.1
homepage: https://github.com/sethladd/bootstrap_for_pub
dependencies:
  jquery_for_pub: any
